name: Build Site

on: [pull_request, push]

jobs:
  build:
    name: Build Site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
        env:
          GATSBY_CONTACT_API_URL: ${{ secrets.GATSBY_CONTACT_API_URL }}
