name: Deploy Site

on:
  push:
    branches:
      - saga

jobs:
  build:
    name: Deploy Site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
        env:
          GATSBY_CONTACT_API_URL: ${{ secrets.GATSBY_CONTACT_API_URL }}
      - name: Deploy
        uses: jakejarvis/s3-sync-action@v0.5.0
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.PROD_AWS_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.PROD_AWS_REGION }}
          SOURCE_DIR: "public"
      - name: Invalidate CloudFront cache
        uses: chetan/invalidate-cloudfront-action@master
        env:
          DISTRIBUTION: ${{ secrets.PROD_AWS_CF_DISTRIBUTION }}
          PATHS: "/*"
          AWS_REGION: ${{ secrets.PROD_AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
